// Stable runtime messages shared by IPC and persisted image failure cards.
const rows = [
  ['The chat was deleted or changed.', 'El chat se ha eliminado o ha cambiado.', 'Le chat a été supprimé ou modifié.', 'Der Chat wurde gelöscht oder geändert.', 'O chat foi eliminado ou alterado.', 'O chat foi excluído ou alterado.', 'La chat è stata eliminata o modificata.', 'Sohbet silindi veya değiştirildi.'],
  ['Download original image', 'Descargar imagen original', 'Télécharger l’image originale', 'Originalbild herunterladen', 'Transferir imagem original', 'Baixar imagem original', 'Scarica immagine originale', 'Özgün görseli indir'],
  ['Original image', 'Imagen original', 'Image originale', 'Originalbild', 'Imagem original', 'Imagem original', 'Immagine originale', 'Özgün görsel'],
  ['The skills library could not be read.', 'No se pudo leer la biblioteca de skills.', 'Impossible de lire la bibliothèque de skills.', 'Die Skill-Bibliothek konnte nicht gelesen werden.', 'Não foi possível ler a biblioteca de skills.', 'Não foi possível ler a biblioteca de skills.', 'Impossibile leggere la libreria di skill.', 'Skill kitaplığı okunamadı.'],
  ['Add a name, description and instructions.', 'Añade un nombre, una descripción e instrucciones.', 'Ajoutez un nom, une description et des instructions.', 'Füge einen Namen, eine Beschreibung und Anweisungen hinzu.', 'Adiciona um nome, uma descrição e instruções.', 'Adicione um nome, uma descrição e instruções.', 'Aggiungi nome, descrizione e istruzioni.', 'Ad, açıklama ve talimatlar ekleyin.'],
  ['The library supports up to 40 skills.', 'La biblioteca admite hasta 40 skills.', 'La bibliothèque accepte jusqu’à 40 skills.', 'Die Bibliothek unterstützt bis zu 40 Skills.', 'A biblioteca permite até 40 skills.', 'A biblioteca permite até 40 skills.', 'La libreria supporta fino a 40 skill.', 'Kitaplık en fazla 40 skill destekler.'],
  ['This conversation has been deleted. Start a new chat.', 'Esta conversación se ha eliminado. Inicia un nuevo chat.', 'Cette conversation a été supprimée. Ouvrez un nouveau chat.', 'Dieses Gespräch wurde gelöscht. Starte einen neuen Chat.', 'Esta conversa foi eliminada. Inicia um novo chat.', 'Esta conversa foi excluída. Inicie um novo chat.', 'Questa conversazione è stata eliminata. Avvia una nuova chat.', 'Bu konuşma silindi. Yeni bir sohbet başlatın.'],
  ['The generated image exceeds 40 MB.', 'La imagen generada supera los 40 MB.', 'L’image générée dépasse 40 Mo.', 'Das erzeugte Bild ist größer als 40 MB.', 'A imagem gerada excede 40 MB.', 'A imagem gerada excede 40 MB.', 'L’immagine generata supera i 40 MB.', 'Oluşturulan görsel 40 MB sınırını aşıyor.'],
  ['Unsupported generated image format.', 'El formato de la imagen generada no es compatible.', 'Le format de l’image générée n’est pas pris en charge.', 'Das Format des erzeugten Bildes wird nicht unterstützt.', 'O formato da imagem gerada não é suportado.', 'O formato da imagem gerada não é compatível.', 'Formato dell’immagine generata non supportato.', 'Oluşturulan görselin biçimi desteklenmiyor.'],
  ['Only one image can be generated per reply. Send another message to create a variation.', 'Solo se puede generar una imagen por respuesta. Envía otro mensaje para crear una variación.', 'Une seule image peut être générée par réponse. Envoyez un autre message pour créer une variante.', 'Pro Antwort kann ein Bild erstellt werden. Sende eine weitere Nachricht für eine Variante.', 'Só é possível gerar uma imagem por resposta. Envia outra mensagem para criar uma variação.', 'Só é possível gerar uma imagem por resposta. Envie outra mensagem para criar uma variação.', 'È possibile generare un’immagine per risposta. Invia un altro messaggio per creare una variante.', 'Her yanıtta bir görsel oluşturulabilir. Bir varyasyon için başka bir mesaj gönderin.'],
  ['Enable Image Atelier in Skills to generate images.', 'Activa Image Atelier en Skills para generar imágenes.', 'Activez Image Atelier dans Skills pour générer des images.', 'Aktiviere Image Atelier unter Skills, um Bilder zu erzeugen.', 'Ativa Image Atelier em Skills para gerar imagens.', 'Ative Image Atelier em Skills para gerar imagens.', 'Attiva Image Atelier in Skills per generare immagini.', 'Görsel oluşturmak için Skills bölümünde Image Atelier’i etkinleştirin.'],
  ['Start a saved chat in Nodi or the assistant to generate an image.', 'Inicia un chat guardado en Nodi o en el asistente para generar una imagen.', 'Ouvrez un chat enregistré dans Nodi ou l’assistant pour générer une image.', 'Starte einen gespeicherten Chat in Nodi oder im Assistenten, um ein Bild zu erzeugen.', 'Inicia um chat guardado no Nodi ou no assistente para gerar uma imagem.', 'Inicie um chat salvo no Nodi ou no assistente para gerar uma imagem.', 'Avvia una chat salvata in Nodi o nell’assistente per generare un’immagine.', 'Görsel oluşturmak için Nodi veya asistanda kayıtlı bir sohbet başlatın.'],
  ['The image brief was interrupted. Retry the response.', 'Las instrucciones de imagen se interrumpieron. Vuelve a generar la respuesta.', 'Les instructions d’image ont été interrompues. Relancez la réponse.', 'Die Bildanweisungen wurden unterbrochen. Erstelle die Antwort erneut.', 'As instruções de imagem foram interrompidas. Gera novamente a resposta.', 'As instruções da imagem foram interrompidas. Gere a resposta novamente.', 'Le istruzioni dell’immagine sono state interrotte. Rigenera la risposta.', 'Görsel talimatları kesildi. Yanıtı yeniden oluşturun.'],
  ['The model returned an invalid image brief. Retry the response.', 'El modelo devolvió instrucciones de imagen no válidas. Vuelve a generar la respuesta.', 'Le modèle a renvoyé des instructions d’image invalides. Relancez la réponse.', 'Das Modell lieferte ungültige Bildanweisungen. Erstelle die Antwort erneut.', 'O modelo devolveu instruções de imagem inválidas. Gera novamente a resposta.', 'O modelo retornou instruções de imagem inválidas. Gere a resposta novamente.', 'Il modello ha restituito istruzioni di immagine non valide. Rigenera la risposta.', 'Model geçersiz görsel talimatları döndürdü. Yanıtı yeniden oluşturun.'],
  ['Choose an image provider and model in Settings.', 'Elige un proveedor y un modelo de imagen en Ajustes.', 'Choisissez un fournisseur et un modèle d’image dans les paramètres.', 'Wähle einen Bildanbieter und ein Modell in den Einstellungen.', 'Escolhe um fornecedor e um modelo de imagem nas Definições.', 'Escolha um provedor e um modelo de imagem nas Configurações.', 'Scegli un fornitore e un modello di immagini nelle impostazioni.', 'Ayarlardan bir görsel sağlayıcısı ve modeli seçin.'],
  ['Image generation failed. Please retry.', 'No se pudo generar la imagen. Vuelve a intentarlo.', 'Impossible de générer l’image. Réessayez.', 'Das Bild konnte nicht erstellt werden. Bitte erneut versuchen.', 'Não foi possível gerar a imagem. Tenta novamente.', 'Não foi possível gerar a imagem. Tente novamente.', 'Impossibile generare l’immagine. Riprova.', 'Görsel oluşturulamadı. Lütfen tekrar deneyin.'],
  ['The image is no longer available.', 'La imagen ya no está disponible.', 'L’image n’est plus disponible.', 'Das Bild ist nicht mehr verfügbar.', 'A imagem já não está disponível.', 'A imagem não está mais disponível.', 'L’immagine non è più disponibile.', 'Görsel artık kullanılamıyor.'],
  ['The image could not be copied.', 'No se pudo copiar la imagen.', 'Impossible de copier l’image.', 'Das Bild konnte nicht kopiert werden.', 'Não foi possível copiar a imagem.', 'Não foi possível copiar a imagem.', 'Impossibile copiare l’immagine.', 'Görsel kopyalanamadı.'],
];
export function localizeChatSkillError(message: string, language: string): string | null {
  const row = rows.find(item => item[0] === message);
  if (!row) return null;
  const index = ['en', 'es', 'fr', 'de', 'pt', 'pt-BR', 'it', 'tr'].indexOf(language);
  return row[index >= 0 ? index : 0];
}
